name: Build Docker Image Locally
on:
  push:
    branches:
      - main
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code 
     uses: actions/checkout@v2
   - name: Checkout code 
     run : docker build -t my-app:latest .
